language: node_js

node_js: 10

services:
  - docker

script:
  - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD" quay.io
  - docker login -u="no-used" -p="$H1_REGISTRY_PASSWORD" 5d08fcb2ca3915e50f7c2c55.registry.pl-waw-1.hyperone.cloud
  - ./build.sh
  - sudo ./test.sh

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
