language: node_js

node_js: 12

services:
  - docker

env:
  - FAMILY=nginx-static,debian-shell
  - FAMILY=node
  - FAMILY=php-apache,php-apache-shell
  - FAMILY=python-passenger

script:
  - npm install
  - NODE=$(which node)
  - $NODE -c ./*/tags.js
  - $NODE ./generate.js -f "$FAMILY" -g
  - git status
  - git diff HEAD
  - test -z "$(git status --porcelain $FAMILY)"
  - $NODE ./generate.js -f "$FAMILY" -b
  - sudo $NODE ./generate.js -f "$FAMILY" -t

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master