language: node_js

node_js: 12

services:
  - docker

script:
  - npm install
  - node ./generate.js
  - git status
  - git diff HEAD
  - test -z "$(git status --porcelain docs)"
  - ./build.sh
  - sudo ./test.sh

deploy:
  provider: script
  script: ./deploy-travis.sh
  on:
    branch: master
