version: '3'

services:
  reverse-proxy:
    image: traefik:v2.3
    command:
      - --api
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme/:/acme/
  php56:
    image: h1cr.io/website/php-apache:5.6
    read_only: true
    build:
      context: php-apache/5.6
    labels:
      - traefik.enable=true
      - traefik.http.services.agent.loadbalancer.server.port=8080
      - traefik.http.routers.php56_80.rule=Host(`php56.127.0.0.1.xip.io`)
      - traefik.http.routers.php56_80.entrypoints=web
    volumes:
      - ./content/:/data/
      - ./content/tmp:/tmp
      - ./content/var/run:/var/run
  php72:
    image: h1cr.io/website/php-apache:7.2
    read_only: true
    build:
      context: php-apache/7.2
    labels:
      - traefik.enable=true
      - traefik.http.services.agent.loadbalancer.server.port=8080
      - traefik.http.routers.php72_80.rule=Host(`php72.127.0.0.1.xip.io`)
      - traefik.http.routers.php72_80.entrypoints=web
    volumes:
      - ./content/:/data/
      - ./content/tmp:/tmp
      - ./content/var/run:/var/run
  nginx:
    image: h1cr.io/website/nginx-static:latest
    read_only: true
    build:
      context: nginx-static/latest
    labels:
      - traefik.enable=true
      - traefik.http.services.agent.loadbalancer.server.port=8080
      - traefik.http.routers.nginx_80.rule=Host(`nginx.127.0.0.1.xip.io`)
      - traefik.http.routers.nginx_80.entrypoints=web
    volumes:
      - ./content/:/data/public
  node:
    image: h1cr.io/website/node:latest
    labels:
      - traefik.enable=true
      - traefik.http.services.agent.loadbalancer.server.port=8080
      - traefik.http.routers.node_80.rule=Host(`node.127.0.0.1.xip.io`)
      - traefik.http.routers.node_80.entrypoints=web
    volumes:
      - ./node/test/:/data/
  theia:
    image: h1cr.io/website/theia:latest
    labels:
      - traefik.enable=true
      - traefik.http.services.agent.loadbalancer.server.port=3000
      - traefik.http.routers.theia_80.rule=Host(`theia.127.0.0.1.xip.io`) && PathPrefix(`/theia/`)
      - traefik.http.middlewares.strip_theia.stripprefix.prefixes=/theia
      - traefik.http.routers.theia_80.entrypoints=web
      - traefik.http.routers.theia_80.middlewares=strip_theia
    volumes:
      - ./node/test/:/home/project