version: '3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: |
      --api --docker
      --entryPoints='Name:http Address::80'
      --entryPoints='Name:https Address::443 TLS'
      --logLevel=DEBUG
    ports:
      - "80:80"     # The HTTP port
      - "8090:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  php56:
    image: h1cr.io/website/php-apache:5.6
    build:
      context: php-apache/5.6
    labels:
      - "traefik.frontend.rule=Host:php56.127.0.0.1.xip.io"
    volumes:
      - ./content/:/data/public
  php72:
    image: h1cr.io/website/php-apache:7.2
    build:
      context: php-apache/7.2
    labels:
      - "traefik.frontend.rule=Host:php72.127.0.0.1.xip.io"
    volumes:
      - ./content/:/data/public
  nginx:
    image: h1cr.io/website/nginx-static:latest
    build:
      context: nginx-static/latest
    labels:
      - "traefik.frontend.rule=Host:nginx.127.0.0.1.xip.io"
    volumes:
      - ./content/:/data/public
